name: test-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - GitPython
  - scikit-image
  - scipy
  - seaborn
  - numpy
  - pandas
  - pathlib
  - python-dateutil>=2.7
  - scikit-image
  - more-itertools
  - statsmodels
  - imageio
  - ipykernel
  - ipython_genutils
  - ipython
  - ipywidgets
  - matplotlib
  - pip:
    - syspath




